name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: create zip deployment 
        uses: actions/checkout@v3
        run: zip -r deploy.zip ./

      # Step 2: Set up PHP
        name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MyApplicationName
        environment_name: MyApplication-Environment
        version_label: 12345
        region: us-west-2
        deployment_package: deploy.zip

      # Step 3: Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --no-scripts --no-progress --prefer-dist

      # Step 4: Install Node.js (for front-end build, if required)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Replace with your Node.js version

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run prod

      # Step 5: Prepare environment variables
      - name: Copy environment file
        run: cp .env.example .env

      - name: Set application key
        run: php artisan key:generate

      # Step 6: Zip the application for deployment
      - name: Create ZIP file
        run: zip -r application.zip . -x "node_modules/*" "vendor/*" "storage/*" "tests/*"

      # Step 7: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      # Step 8: Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          pip install awsebcli --upgrade
          eb init -p php -r us-east-1 app-name # Replace `app-name` with your Elastic Beanstalk app name
          eb use environment-name # Replace `environment-name` with your Elastic Beanstalk environment name
          eb deploy
